### ISSUE TITLE
Undefined subroutine &main::abs_path

### ISSUE THREAD

**Issue by greduan** [norbusan/kobo-ja-dict-enhance#4]
Heya, so I tried on macOS Catalina and on Arch Linux and I keep getting the above error whenever I run the script.

I've downloaded the latest `edict2` from the link on your blog post and I have the `dicthtml-jaxxdjs.zip` in the directory properly as well.

But when I run `perl enhance-dictionary.pl` I get the above error.

Any ideas?

**Comment by reidevries** [comment]
I had this error, I think it's due to the switch from Cwd to File::Spec. I fixed it by changing "abs_path" on line 332 to "File::Spec->rel2abs" to use the File::Spec version of the function. I also had to do yay -S perl-perlio-gzip on arch to get the perlio layer for gzip. maybe i'll do a pull request, never done one of those, exciting :dancing_women:

**Comment by norbusan** [comment]
Oh, I have somehow not seen this report. Yes, one `abs_path` wasn't replaced in the last commit. Done this now. Should be fine now. Sorry
